### PR TITLE
feat: Add support for @nestjs version 10

### PR DESCRIPTION
**Pull request by TylerHAtkinson**
# Description

Adding support for nestjs version 10

# Type of change

> Please select the options that are relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (non-breaking change which does not add functionality)

# Checklist:

- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by stelescuraul** [comment]
@ahmadnazir can you approve the tests to run ?
I wonder if this could go out as a major version or a minor 🤔

**Comment by ashunshah** [comment]
Any plans to merge this?

**Comment by stelescuraul** [comment]
Since I don't have maintainer role in the project, I am not sure I can help getting this forward.
Unless @ahmadnazir / @rpacevics take a look at this, my best suggestion is to fork it.

**Comment by ahmadnazir** [comment]
@ashunshah I apologize for the delay here. We are handing over the keys to @stelescuraul who was the mastermind behind this project and we weren't able to dedicate resources to maintain it after he moved on to another role. Hopefully, this will get some attention now.

**Review by stelescuraul — APPROVED** [review]

**Pull request merged**
